name: Lint and Test Charts

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (lint)
        working-directory: helm
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --chart-dirs . --all

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0

      - name: Run chart-testing (install)
        working-directory: helm
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --chart-dirs . --all --helm-extra-set-args '--set=frontend.service.type=ClusterIP'
